name: ByteCloudAPI
version: mvn:unknown

author: §cByteList
website: https://bytelist.de/

main: de.bytelist.bytecloud.core.ByteCloudCore

#load: STARTUP
loadbefore: [GameChest, ClickAttack, Lobby, ShulkerDefence, JumpDuell, Survival, DeathRun]

commands:
   cloud: