name: ByteCloudAPI
version: mvn:unknown
#description
author: ByteList
main: de.bytelist.bytecloud.core.ByteCloudCore

loadbefore: [GameChest]

commands:
   cloud:
   goto:
   join:
   server:
   stop: