name: ByteCloudAPI
version: 2.1

author: §cByteList
website: https://bytelist.de/

main: de.bytelist.bytecloud.core.ByteCloudCore

#load: STARTUP
loadbefore: [GCGeneral, ClickAttack, Lobby, ShulkerDefence, JumpDuell, Survival, DeathRun]